actions debug

diff --git a/.github/workflows/update-stats-action.yaml b/.github/workflows/update-stats-action.yaml
--- a/.github/workflows/update-stats-action.yaml
+++ b/.github/workflows/update-stats-action.yaml
@@ -2,57 +2,57 @@ name: push-stats-action
 on:
   workflow_dispatch:
   schedule:
-  - cron: "0 0 * * 1"
+    - cron: "0 0 * * 1"
 
 jobs:
   push-stats:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Create data directory
-      run: |
-        mkdir -p _data
+      - name: Create data directory
+        run: |
+          mkdir -p _data
 
-    - name: Fetch waka stats
-      run: |
-        # fetch json using curl, if error, retry 3 times
-        for i in {1..3}; do 
-          curl -s "https://wakatime.com/share/@0269a873-ebe8-43fc-8ead-f0560fa51bae/51e6363c-2acb-4d8c-b282-835d52d97893.json" > assets/misc/waka_tmp.json
-          if ! grep -q "error" assets/misc/waka_tmp.json;
-            then
-              echo "Waka stats fetched successfully"
-              mv assets/misc/waka_tmp.json assets/misc/waka.json
-              break
-            else
-              echo "Waka stats fetch failed, retrying..."
-              rm assets/misc/waka_tmp.json
+      - name: Fetch waka stats
+        run: |
+          # fetch json using curl, if error, retry 3 times
+          for i in {1..3}; do 
+            curl -s "https://wakatime.com/share/@0269a873-ebe8-43fc-8ead-f0560fa51bae/51e6363c-2acb-4d8c-b282-835d52d97893.json" > assets/misc/waka_tmp.json
+            if ! grep -q "error" assets/misc/waka_tmp.json;
+              then
+                echo "Waka stats fetched successfully"
+                mv assets/misc/waka_tmp.json assets/misc/waka.json
+                break
+              else
+                echo "Waka stats fetch failed, retrying..."
+                rm assets/misc/waka_tmp.json
+            fi
+          done
+
+      - name: Fetch stackoverflow reputation
+        run: |
+          curl -s "https://stackoverflow.com/users/flair/2329060.json" > _data/stackoverflow_reputation.json
+
+      - name: Fetch stackoverflow tags
+        run: |
+          curl -s --compressed 'https://api.stackexchange.com/2.3/users/2329060/tags?pagesize=100&order=desc&sort=popular&site=stackoverflow&filter=!bMsg5CXICfJ)0K' > _data/stackoverflow_tags.json
+
+      - name: Fetch ai stackexchange reputation
+        run: |
+          curl -s "https://ai.stackexchange.com/users/flair/12841.json" > _data/ai_reputation.json
+
+      - name: Fetch ai stackexchange tags
+        run: |
+          curl -s --compressed 'https://api.stackexchange.com/2.3/users/12841/tags?pagesize=100&order=desc&sort=popular&site=ai&filter=!bMsg5CXICfJ)0K' > _data/ai_tags.json
+
+      - name: Push stats
+        run: |
+          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+          git add .
+          git status
+          if [ -n "$(git status --porcelain)" ]; then
+            git commit -m "Update stats"
+            git push
           fi
-        done
-        ls assets/misc
-
-    - name: Fetch stackoverflow reputation
-      run: |
-        curl -s "https://stackoverflow.com/users/flair/2329060.json" > _data/stackoverflow_reputation.json
-
-    - name: Fetch stackoverflow tags
-      run: |
-        curl -s --compressed 'https://api.stackexchange.com/2.3/users/2329060/tags?pagesize=100&order=desc&sort=popular&site=stackoverflow&filter=!bMsg5CXICfJ)0K' > _data/stackoverflow_tags.json
-    
-    - name: Fetch ai stackexchange reputation
-      run: |
-        curl -s "https://ai.stackexchange.com/users/flair/12841.json" > _data/ai_reputation.json
-    
-    - name: Fetch ai stackexchange tags
-      run: |
-        curl -s --compressed 'https://api.stackexchange.com/2.3/users/12841/tags?pagesize=100&order=desc&sort=popular&site=ai&filter=!bMsg5CXICfJ)0K' > _data/ai_tags.json
-    
-    - name: Push stats
-      run: |
-        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
-        git config --local user.name "github-actions[bot]"
-        git add .
-        if [ -n "$(git status --porcelain)" ]; then
-          git commit -m "Update stats"
-          git push
-        fi 
